Global:
  use_gpu: true
  epoch_num: 1000
  log_smooth_window: 20
  print_batch_step: 10
  save_model_dir: ./output_2/cls/mv3_4/
  save_epoch_step: 3
  eval_batch_step:
  - 0
  - 50
  cal_metric_during_train: true
  pretrained_model: ./output_2/cls/mv3_3/best_accuracy
  checkpoints: null
  save_inference_dir: null
  use_visualdl: false
  infer_img: doc/imgs_words_en/word_10.png
  label_list:
  - '0'
  - '15'
  - '30'
  - '45'
  - '60'
  - '75'
  - '90'
  - '105'
  - '120'
  - '135'
  - '150'
  - '165'
  - '180'
  - '195'
  - '210'
  - '225'
  - '240'
  - '255'
  - '270'
  - '285'
  - '300'
  - '315'
  - '330'
  - '345'
  use_wandb: true
  wandb:
    project: text_ang_cls
    entity: zatoichi
    name: 46k_ang_cls_20220828_0804
Architecture:
  model_type: cls
  algorithm: CLS
  Transform: null
  Backbone:
    name: MobileNetV3
    scale: 0.35
  model_name: small
  Neck: null
  Head:
    name: ClsHead
    class_dim: 24
Loss:
  name: ClsLoss
Optimizer:
  name: Adam
  beta1: 0.9
  beta2: 0.999
  lr:
    name: Cosine
    learning_rate: 0.001
  regularizer:
    name: L2
    factor: 0
PostProcess:
  name: ClsPostProcess
Metric:
  name: ClsMetric
  main_indicator: acc
Train:
  dataset:
    name: SimpleDataSet
    data_dir: /home/zatoichi/Code/ANGLE_CLS/PP_ANG_DET_2_24/
    label_file_list:
    - /home/zatoichi/Code/ANGLE_CLS/PP_ANG_DET_2_24/cls_gt_train.txt
    transforms:
    - DecodeImage:
        img_mode: BGR
        channel_first: false
    - ClsLabelEncode: null
    - RecAug:
        use_tia: false
    - RandAugment: null
    - ClsResizeImg:
        image_shape:
        - 3
        - 48
        - 192
    - KeepKeys:
        keep_keys:
        - image
        - label
  loader:
    shuffle: true
    batch_size_per_card: 512
    drop_last: true
    num_workers: 8
Eval:
  dataset:
    name: SimpleDataSet
    data_dir: /home/zatoichi/Code/ANGLE_CLS/PP_ANG_DET_2_24/
    label_file_list:
    - /home/zatoichi/Code/ANGLE_CLS/PP_ANG_DET_2_24/cls_gt_test.txt
    transforms:
    - DecodeImage:
        img_mode: BGR
        channel_first: false
    - ClsLabelEncode: null
    - ClsResizeImg:
        image_shape:
        - 3
        - 48
        - 192
    - KeepKeys:
        keep_keys:
        - image
        - label
  loader:
    shuffle: false
    drop_last: false
    batch_size_per_card: 512
    num_workers: 24
profiler_options: null
