Global:
  use_gpu: true
  epoch_num: 20
  log_smooth_window: 20
  print_batch_step: 10
  #  save_model_dir: ./output/quant_model/
  save_epoch_step: 1
  eval_batch_step:
  - 0
  - 10
  cal_metric_during_train: true
  pretrained_model: /home/zatoichi/Code/ANGLE_CLS/output/cls/mv3/best_accuracy
  checkpoints: null
  save_inference_dir: null
  use_visualdl: false
  infer_img: doc/imgs_words_en/word_10.png
  label_list:
  - '0'
  - '45'
  - '90'
  - '135'
  - '180'
  - '225'
  - '270'
  - '315'
  use_wandb: true
  wandb:
    entity: zatoichi
    name: 6k_ang_cls_20220822_2240
    project: text_ang_cls
Architecture:
  model_type: cls
  algorithm: CLS
  Transform: null
  Backbone:
    name: MobileNetV3
    scale: 0.35
    model_name: small
  Neck: null
  Head:
    name: ClsHead
    class_dim: 8
Loss:
  name: ClsLoss
Optimizer:
  name: Adam
  beta1: 0.9
  beta2: 0.999
  lr:
    name: Cosine
    learning_rate: 0.001
  regularizer:
    name: L2
    factor: 0
PostProcess:
  name: ClsPostProcess
Metric:
  name: ClsMetric
  main_indicator: acc
Train:
  dataset:
    name: SimpleDataSet
    data_dir: /home/zatoichi/Code/ANGLE_CLS/PP_ANG_DET/
    label_file_list:
    - /home/zatoichi/Code/ANGLE_CLS/PP_ANG_DET/cls_gt_train.txt
    transforms:
    - DecodeImage:
        img_mode: BGR
        channel_first: false
    - ClsLabelEncode: null
    - RecAug:
        use_tia: false
    - RandAugment: null
    - ClsResizeImg:
        image_shape:
        - 3
        - 48
        - 192
    - KeepKeys:
        keep_keys:
        - image
        - label
  loader:
    shuffle: true
    batch_size_per_card: 512
    drop_last: true
    num_workers: 8
Eval:
  dataset:
    name: SimpleDataSet
    data_dir: /home/zatoichi/Code/ANGLE_CLS/PP_ANG_DET/
    label_file_list:
    - /home/zatoichi/Code/ANGLE_CLS/PP_ANG_DET/cls_gt_test.txt
    transforms:
    - DecodeImage:
        img_mode: BGR
        channel_first: false
    - ClsLabelEncode: null
    - ClsResizeImg:
        image_shape:
        - 3
        - 48
        - 192
    - KeepKeys:
        keep_keys:
        - image
        - label
  loader:
    shuffle: false
    drop_last: false
    batch_size_per_card: 512
    num_workers: 16
profiler_options: null
